### ISSUE TITLE
Bot crashes on receiving !playurl command without HTML formatting

### ISSUE THREAD

**Issue by BafDyce** [BafDyce/botamusique#51]
**Describe the bug**
See Steps to reproduce.

**Affected version**
be6b4d4088ccfa52b9b2642826b9a507f5bc73e0

**Steps To Reproduce**
1. Send the bot a private message with a `!playurl <url>` command without HTML formatting of the message.
2. The bot crashes and disconnects from mumble

**Expected behavior**
The bot should play the given sound file.

**Screenshots/Log**

```
Traceback (most recent call last):
  File "mumbleBot.py", line 350, in <module>
    botamusique = MumbleBot(args)
  File "mumbleBot.py", line 80, in __init__
    self.loop()
  File "mumbleBot.py", line 308, in loop
    self.launch_next()
  File "mumbleBot.py", line 238, in launch_next
    url = m.group(1)
AttributeError: 'NoneType' object has no attribute 'group'
bot exited with return code 1
```

**Comment by BafDyce** [comment]
I think this issue was fixed by [this addition](https://github.com/azlux/botamusique/commit/7057252420c89c3d1ff08efc66605f9c996b1a27#diff-e559958b8af833062608cac74071172bR70) in an upstream change.
We should wait until #52 was reviewed & merged, then check whether the issue still exists.

**Comment by BafDyce** [comment]
Great. Thanks for your input! Closing this now.
